#!/usr/bin/env bash
# is a factors challenge

check_factor()
{

	if [ $# -ne 3 ];
		then
				args=("$@")
				counter=0
				count2=1
				for a in ${args[*]};
				do
						if [ $counter -gt 1 ];
						then
								count2=$(echo $a*$count2 | bc)
						fi
						counter=$((counter + 1))
				done
		else
				count2=$3
		fi


		count1=$2
		coun=$(echo "$1" | tr ':' '=')

		result=$(echo "if($count2 > $count1) 1 else 0" | bc)
			if ((result == 1)); then
				countcp=$count1
				count1=$count2
				count2=$countcp
				fi

		echo "$coun$count1*$count2"
}


if [ $# -ne 1 ]
then
		echo 'Usage: factors <file>'
		exit 1
else

		while read i
		do

				res_done=$(factor "$i")
				check_factor $res_done

		done < "$1"
fi
