#!/usr/bin/env bash
# is a factors challenge

check_factor()
{
	if [ $# -ne 3 ];
		then
				args=("$@")
				counter=0
				counter2=1
				for a in ${args[*]};
				do
						if [ $counter -gt 1 ];
						then
								counter2=$(echo $a*$counter2 | bc)
						fi
						counter=$((counter + 1))
				done
		else
				counter2=$3
		fi

		counter1=$2
		count=$(echo "$1" | tr ':' '=')

		result=$(echo "if($counter2 > $counter1) 1 else 0" | bc)
			if ((result == 1)); then
				countcp=$counter1
				counter1=$counter2
				counter2=$countcp
				fi

		echo "$count$counter1*$counter2"
}

if [ $# -ne 1 ]
then
		echo 'Usage: rsa <file>'
		exit 1
else

		while read i
		do

				res_done=$(factor "$i")
				check_factor $res_done

		done < "$1"
fi
